# Generated by Django 3.2.25 on 2025-05-02 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('wh_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('wh_name', models.CharField(max_length=100)),
                ('wh_bg', models.CharField(blank=True, max_length=100, null=True)),
                ('wh_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_create_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
